# Generated by Django 5.2.17 on 2026-09-28 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RegistrationAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('country', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name_plural': 'registration authorities',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=220)),
                ('slug', models.SlugField(max_length=230, unique=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('verification_state', models.CharField(choices=[('community', 'Community submitted'), ('source', 'Source attached'), ('identity', 'Identity reviewed'), ('pedigree', 'Pedigree reviewed'), ('health', 'Health/DNA verified')], db_index=True, default='community', max_length=20)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dammed_offspring', to='registry.dog')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sired_offspring', to='registry.dog')),
                ('kennel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to='registry.kennel')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('pedigree', 'Pedigree document'), ('registry', 'Registry record'), ('health', 'Health/DNA document'), ('breeder', 'Breeder supplied'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('source_url', models.URLField(blank=True)),
                ('document', models.FileField(blank=True, upload_to='evidence/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='registry.dog')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=160)),
                ('tested_on', models.DateField(blank=True, null=True)),
                ('verification_state', models.CharField(choices=[('community', 'Community submitted'), ('source', 'Source attached'), ('identity', 'Identity reviewed'), ('pedigree', 'Pedigree reviewed'), ('health', 'Health/DNA verified')], default='community', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='registry.dog')),
            ],
            options={
                'ordering': ('test_type', '-tested_on'),
            },
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dammed_litters', to='registry.dog')),
                ('kennel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters', to='registry.kennel')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sired_litters', to='registry.dog')),
            ],
            options={
                'ordering': ('-date_of_birth', 'code'),
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='registry.litter'),
        ),
        migrations.CreateModel(
            name='DogRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=120)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registry.dog')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registry.registrationauthority')),
            ],
        ),
        migrations.CreateModel(
            name='DogAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='registry.dog')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dog', 'name'), name='unique_dog_alias')],
            },
        ),
        migrations.CreateModel(
            name='DogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='dogs/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='registry.dog')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('dog',), name='one_primary_image_per_dog')],
            },
        ),
        migrations.CreateModel(
            name='KennelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('contributor', 'Contributor')], default='contributor', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='registry.kennel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kennel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kennel', 'user'), name='unique_kennel_member')],
            },
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['is_public', 'verification_state'], name='registry_do_is_publ_acb31d_idx'),
        ),
        migrations.AddConstraint(
            model_name='dogregistration',
            constraint=models.UniqueConstraint(fields=('authority', 'number'), name='unique_registration_number_per_authority'),
        ),
    ]
